name: deepSORT
channels:
  - defaults
dependencies:
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py36_0
  - libedit=3.1.20191231
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1g
  - pip=20.2.2=py36_0
  - python=3.6.10
  - readline=8.0
  - setuptools=49.6.0=py36_0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.35.1=py_0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.10.0
    - astor==0.8.1
    - gast==0.2.2
    - google-pasta==0.2.0
    - grpcio==1.31.0
    - h5py==2.10.0
    - importlib-metadata==1.7.0
    - joblib==0.16.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - markdown==3.2.2
    - numpy==1.19.1
    - opencv-python==4.4.0.42
    - opt-einsum==3.3.0
    - protobuf==3.13.0
    - scikit-learn==0.22.2
    - scipy==1.5.2
    - six==1.15.0
    - tensorboard==1.15.0
    - tensorflow==1.15.0
    - tensorflow-estimator==1.15.1
    - termcolor==1.1.0
    - threadpoolctl==2.1.0
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - zipp==3.1.0

